# Source: AffiliateMarketing.API/Controllers/ReferralLinksController.cs
import uuid
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.db import get_db
from app.core.config import settings
from app.core.security import require_affiliate
from app.schemas.affiliate import (
    GenerateLinkRequest, GenerateLinkResponse,
    ValidateReferralRequest, ValidationResultResponse,
    RecordConversionRequest,
)
from app.services import affiliate_service, referral_service

router = APIRouter(prefix="/affiliate/api/v1/links", tags=["03. Referral Engine"])


@router.post("/generate", response_model=GenerateLinkResponse)
async def generate_link(
    request: GenerateLinkRequest,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(require_affiliate),
):
    """[Affiliate only] Generate a unique tracking link for a product."""
    affiliate_profile_id_str = current_user.get("affiliate_profile_id")
    if not affiliate_profile_id_str:
        raise HTTPException(status_code=400, detail="No affiliate profile linked to this account")

    try:
        code = await affiliate_service.generate_link(
            db,
            uuid.UUID(affiliate_profile_id_str),
            request.product_id,
            request.source_platform,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    tracking_url = f"{settings.APP_BASE_URL}/api/v1/r/{code}"
    return GenerateLinkResponse(
        referral_code=code,
        tracking_url=tracking_url,
        source_platform=request.source_platform,
    )


@router.post("/validate", response_model=ValidationResultResponse)
async def validate_referral(
    request: ValidateReferralRequest,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_affiliate),
):
    """[Affiliate only] Validate a referral code before recording a purchase."""
    return await referral_service.validate_referral(
        db, request.referral_code, request.purchasing_user_id, request.product_id
    )


@router.post("/record-conversion")
async def record_conversion(
    request: RecordConversionRequest,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_affiliate),
):
    """[Affiliate only] Record an attributed purchase conversion."""
    try:
        conversion = await referral_service.record_conversion(
            db,
            request.referral_code,
            request.purchasing_user_id,
            request.product_id,
            request.sale_amount,
            request.customer_country,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return {
        "id": str(conversion.id),
        "commission_earned": float(conversion.commission_earned),
        "is_under_review": conversion.is_under_review,
        "message": "Under review — pending fraud check" if conversion.is_under_review else "Conversion recorded",
    }


@router.get("/my-links")
async def my_links(
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(require_affiliate),
):
    """[Affiliate only] List all referral links generated by the authenticated affiliate."""
    from sqlalchemy import select
    from app.models.referral_link import ReferralLink
    profile_id_str = current_user.get("affiliate_profile_id")
    if not profile_id_str:
        return []
    result = await db.execute(
        select(ReferralLink)
        .where(ReferralLink.affiliate_profile_id == uuid.UUID(profile_id_str))
        .order_by(ReferralLink.created_at.desc())
    )
    links = result.scalars().all()
    base = settings.APP_BASE_URL
    return [
        {
            "referral_code": lnk.generated_code,
            "tracking_url": f"{base}/api/v1/r/{lnk.generated_code}",
            "product_id": str(lnk.product_id),
            "source_platform": lnk.source_platform,
            "is_active": lnk.is_active,
            "created_at": lnk.created_at.isoformat(),
        }
        for lnk in links
    ]
