<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Affiliate.Events\Affiliate.Events.csproj" />
    <ProjectReference Include="..\AffiliateMarketing.Contracts\AffiliateMarketing.Contracts.csproj" />
    <ProjectReference Include="..\AffiliateMarketing.Domain\AffiliateMarketing.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Identity\Queries\" />
    <Folder Include="Tracking\Commands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

</Project>
